### PR TITLE
Refactor judger code

### PR DESCRIPTION
**Pull request by slhmy**
This PR merge judger-server into judger & remove judger-cli & judger-service.
Also, some unnecessary code in judger is erased (Ex. the judge API in judger).

Folder under judger is reorganized, so currently it becomes more similiar with the structure of oj-platform-service.

More option is take into the front to increase the flexibilty for judger launch.

### CODE REVIEW

**Comment by Zztrans** [comment]
It seems structured like this:

- `cli`  -> `agent`, including `platform` and `rclone`.

- `service` -> `handler`

- `worker.rs` control agent and handler judge event flow.

- `main.rs` listened to HTTP request and called the worker.

LGFM, which seems to be clearer.

**Review by KanadeSiina — APPROVED** [review]
LGTM, they should be in a single module.

**Comment by slhmy** [comment]
> It seems structured like this:
> 
> * `cli`  -> `agent`, including `platform` and `rclone`.
> * `service` -> `handler`
> * `worker.rs` control agent and handler judge event flow.
> * `main.rs` listened to HTTP request and called the worker.
> 
> LGFM, which seems to be clearer.

Should be notice that, we still need service mod in the future. Sevice mod will hold a set of more logical funcs instead of web server handlers.

**Comment by slhmy** [comment]
I'm merging it since everyone think it's fine. But some feature may be broken after refactor.

**Pull request merged**
